package org.f24.service.pdf.util;

public enum FieldEnum {

    DELEGATION("attorney"),
    AGENCY("agency"),
    AGENCY_PROVINCE("agencyProvince"),
    ATTORNEY("attorney"),
    BIRTH_PROVINCE("province"),
    TAX_PROVINCE("domicileProvince"),
    TAX_CODE("taxCode"),
    CORPORATE_NAME("corporateName"),
    SURNAME("surname"),
    NAME("name"),
    BIRTH_DATE("dateOfBirth"),
    SEX("sex"),
    BIRTH_PLACE("municipalityOfBirth"),
    MUNICIPALITY("municipality"),
    ADDRESS("address"),
    RELATIVE_TAX_CODE("receiverTaxCode"),
    ID_CODE("idCode"),
    TAX_TYPE_CODE("tributeCode"),
    INSTALLMENT("installment"),
    YEAR("reportingYear"),
    DOCUMENT_CODE("deedCode"),
    OFFICE_CODE("locationCode"),
    OFFICE_CODE_TREASURY("officeCode"),
    CONTRIBUTION_REASON("contributionReason"),
    INPS_CODE("inpsCode"),
    START_DATE("startDate"),
    END_DATE("endDate"),
    REGION_CODE("regionCode"),
    OPERATION_ID("operationId"),
    MUNICIPALITY_CODE("municipalityCode"),
    RECONSIDERATION("ravv"),
    PROPERTIES_CHANGED("building"),
    ADVANCE_PAYMENT("acc"),
    FULL_PAYMENT("balance"),
    NUMBER_OF_PROPERTIES("numberOfBuildings"),
    INSTITUTION("institution"),
    MONTH("month"),
    DATE_OF_PAYMENT("dateOfPayment"),
    COMPANY("company"),
    CAB_CODE("cabCode"),
    CHECK_NUMBER("checkNumber"),
    ABI_CODE("abiCode"),
    BANK("isBank"),
    CIRCULAR("isCircular"),
    IBAN_CODE("ibanCode"),
    COMPANY_CODE("companyCode"),
    CONTROL_CODE("controlCode"),
    REFERENCE_NUMBER("referenceNumber"),
    REASON("reason"),
    INSTITUTION_CODE("institutionCode"),
    POSITION_CODE("positionCode"),
    TYPE("type"),
    ID_ELEMENTS("idElements"),
    BANK_ACCOUNT_NUMBER("bankAccountNumber"),
    BANK_ID("bankId"),
    SECTION("section"),
    IS_NOT_TAX_YEAR("calendarYear"),
    HEADER("header"),
    TAX_PAYER("contributor"),
    PERSONAL_DATA("personalData"),
    TAX_ADDRESS("taxResidence"),
    TREASURY("treasury"),
    INPS("inps"),
    REGION("region"),
    LOCAL_TAX_PAY("imu"),
    INAIL("inail"),
    SOCIAL_SECURITY("socialSecurity"),
    PAYMENT_DETAILS("paymentDetails"),
    EXCISE("excise"),
    DEDUCTION("deduction"),
    DEBIT_AMOUNT("debitAmount"),
    CREDIT_AMOUNT("creditAmount"),
    TOTAL_AMOUNT("totalAmount"),
    TOTAL_DEBIT("totalDebitAmount"),
    TOTAL_CREDIT("totalCreditAmount"),
    SIGNATURE("signature");

    private String name;

    FieldEnum(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

}
